# shellcheck shell=bash
# sourced by repo.sh: tracks which upstream packaging commit we built from
# metadata sits next to the patches in pkgs/<pkg>, committed with the repo
# upstream = hash our current artifacts were built from
# checked  = last run that saw them up to date
# patches  = content sha of pkgs/<pkg>/*.patch they were built with
# rev      = patch revision, rel suffix is rel_base + rev

# shellcheck disable=SC2034 # read by repo.sh
meta_name=.RPKGINFO
# shellcheck disable=SC2034 # read by repo.sh
rel_base=90

# same format as git --date=iso, so both lines read alike
now() {
	date '+%Y-%m-%d %H:%M:%S %z'
}

# "<hash> <iso date>" of the cloned packaging repo head
upstream_head() {
	git -C "$1" log -1 --format='%H %cd' --date=iso
}

# packaging repo url, devtools' own name mapping so it tracks pkgctl
# child bash: devtools libs break under set -u and leak exports
packaging_url() {
	# shellcheck disable=SC2016 # expanded by the child
	bash -c 'source /usr/share/devtools/lib/api/gitlab.sh
		printf "%s/%s.git\n" "$GIT_PACKAGING_URL_HTTPS" \
			"$(gitlab_project_name_to_path "$1")"' _ "$1"
}

# makepkg.conf value, same lookup as makepkg: env, user conf, system conf
# child bash: config sourcing leaks globals and readonly arrays
makepkg_conf() {
	# shellcheck disable=SC2016 # expanded by the child
	bash -c 'source /usr/share/makepkg/util/config.sh
		load_makepkg_config
		printf "%s\n" "${!1:-}"' _ "$1"
}

# "Name <mail>", placeholders rejected like pkgctl repo configure does
# makechrootpkg reads it too, unset shows "Unknown Packager" in .PKGINFO
is_packager_valid() {
	[[ $1 =~ ^(.+)\ \<.+@.+\>$ ]] || return 1
	[[ ${BASH_REMATCH[1]} != "John Doe" &&
		${BASH_REMATCH[1]} != "Unknown Packager" ]]
}

# primary fingerprints of a key selector or key file, one per line
key_fprs() {
	gpg --with-colons "$@" | awk -F: '
		$1 == "pub" || $1 == "sec" { want = 1; next }
		$1 == "fpr" && want { print $10; want = 0 }'
}

# key must be usable here and shipped in the pubkey file,
# else users' pacman rejects what this machine signs
validate_signing_key() {
	local key=$1 pub=$2 fpr
	if [[ -z $key ]]; then
		echo "GPGKEY unset in makepkg.conf" >&2
		return 1
	fi
	fpr=$(key_fprs --list-secret-keys "$key") || {
		echo "GPGKEY $key: no secret key in keyring" >&2
		return 1
	}
	if ! grep -qx "$fpr" < <(key_fprs --show-keys "$pub"); then
		echo "GPGKEY $fpr missing from $pub, export it there" >&2
		return 1
	fi
}

# packaging repo head hash without cloning
# explicit failures: callers in || context run without errexit
remote_head() {
	local url out
	url=$(packaging_url "$1") || return 1
	out=$(git ls-remote "$url" HEAD) || return 1
	[[ -n $out ]] || { echo "$1: no HEAD at $url" >&2; return 1; }
	echo "${out%%[[:space:]]*}"
}

# value of a key, empty when file or key missing
meta_get() {
	[[ -f $1 ]] || return 0
	sed -n "s/^$2 = //p" "$1"
}

# content only, renaming a patch doesn't count as a change
patches_sum() {
	local out
	out=$(cat "$1"*.patch | sha256sum)
	echo "${out%% *}"
}

# patches carry PKGBUILD changes only, .SRCINFO is regenerated from it
# run from / since git inside a repo drops paths outside the cwd prefix
# unreadable patches fail too, a guard must not pass on error
validate_patches() {
	local stat
	stat=$(git -C / apply --numstat "$(realpath "$1")"/*.patch) || return 1
	if [[ $stat == *$'\t'.SRCINFO* ]]; then
		echo "$1: patches touch .SRCINFO, keep them to PKGBUILD" >&2
		return 1
	fi
}

# when the patches differ from what the artifacts were built with
has_patches_changed() {
	[[ $(meta_get "$1" patches) != "$2" ]]
}

# bumps on every patch change and never resets, so the suffix only grows
# and a filename is never reused, even across upstream version bumps
next_rev() {
	local rev
	rev=$(meta_get "$1" rev)
	# no record: first build, or existing artifacts being bootstrapped
	[[ -n $rev ]] || { echo 0; return; }
	has_patches_changed "$1" "$2" && rev=$((rev + 1))
	echo "$rev"
}


# upstream commits since our record, what to review against our patches
upstream_log() {
	local old
	old=$(meta_get "$2" upstream)
	[[ -n $old ]] || return 0
	# rewritten history drops our hash from the clone, no range to show
	if ! git -C "$1" cat-file -e "$old^{commit}"; then
		echo "$1: recorded $old gone upstream, force push?" >&2
		return 0
	fi
	git -C "$1" log --oneline "$old..HEAD"
}

# every recorded package file still in dest, -debug may never exist
# no record counts as missing
has_artifacts() {
	local f
	[[ -n $(meta_get "$1" file) ]] || return 1
	while read -r f; do
		[[ -f $2/$f || $f == *-debug-* ]] || return 1
	done < <(meta_get "$1" file)
}

# full rewrite, only after artifacts match this upstream head
# args: clone meta rev patches_sum, then package file paths built
write_meta() {
	local clone=$1 meta=$2 rev=$3 sum=$4 hash date f
	shift 4
	read -r hash date < <(upstream_head "$clone")
	{
		echo "# generated by repack.sh"
		echo "upstream = $hash"
		echo "upstream_date = $date"
		echo "checked = $(now)"
		echo "patches = $sum"
		echo "rev = $rev"
		for f; do
			echo "file = ${f##*/}"
		done
	} > "$meta"
}

# bump check time, keeps the upstream hash artifacts came from
touch_meta() {
	[[ -f $1 ]] || return 1
	sed -i "s/^checked = .*/checked = $(now)/" "$1"
}

# why a package needs a build: "moved" and/or "patched", else "missing"
# when recorded artifacts are gone from dest, empty when up to date
# read-only, no clone: safe for CI checks. args: pkg meta patches_sum dest
# upstream: hash compare only, commit dates lie (rebase, amend, tz)
build_reasons() {
	local head out=()
	head=$(remote_head "$1") || {
		echo "$1: upstream lookup failed" >&2
		return 1
	}
	[[ $head != "$(meta_get "$2" upstream)" ]] && out+=(moved)
	has_patches_changed "$2" "$3" && out+=(patched)
	((${#out[@]})) || has_artifacts "$2" "$4" || out+=(missing)
	echo "${out[*]}"
}

# binaries live on their own branch, one commit replaced on each publish,
# so master history stays text. layout: <repo>/<arch>/ at its root
# shellcheck disable=SC2034 # read by publish.sh
dist_branch=dist

# published branch into FETCH_HEAD, 2 when it was never published
# ls-remote first: a plain fetch can't tell missing from network errors
fetch_dist() {
	local rc=0
	git ls-remote --exit-code --heads origin "$dist_branch" || rc=$?
	((rc == 0)) || return "$rc"
	git fetch origin "$dist_branch"
}

# fresh machine or CI: seed out/ from the published branch so skip checks
# see what users have, else same names get rebuilt. args: out_dir repo_db
# a local db may be ahead of the published one, never overwrite it
seed_out() {
	local rc=0
	[[ -e $2 ]] && return 0
	fetch_dist || rc=$?
	# never published: nothing to seed, first build
	((rc == 2)) && return 0
	((rc == 0)) || return 1
	mkdir -p "$1"
	git archive FETCH_HEAD | tar -x -C "$1"
}
