# shellcheck shell=bash
# sourced by repo.sh: tracks which upstream packaging commit we built from
# metadata sits next to the patches in pkgs/<pkg>, committed with the repo
# upstream = hash our current artifacts were built from
# checked  = last run that saw them up to date
# patches  = content sha of pkgs/<pkg>/*.patch they were built with
# rev      = patch revision, rel suffix is rel_base + rev

# shellcheck disable=SC2034 # read by repo.sh
meta_name=.RPKGINFO
# shellcheck disable=SC2034 # read by repo.sh
rel_base=90

# same format as git --date=iso, so both lines read alike
now() {
	date '+%Y-%m-%d %H:%M:%S %z'
}

# "<hash> <iso date>" of the cloned packaging repo head
upstream_head() {
	git -C "$1" log -1 --format='%H %cd' --date=iso
}

# packaging repo url, devtools' own name mapping so it tracks pkgctl
# child bash: devtools libs break under set -u and leak exports
packaging_url() {
	# shellcheck disable=SC2016 # expanded by the child
	bash -c 'source /usr/share/devtools/lib/api/gitlab.sh
		printf "%s/%s.git\n" "$GIT_PACKAGING_URL_HTTPS" \
			"$(gitlab_project_name_to_path "$1")"' _ "$1"
}

# packaging repo head hash without cloning
remote_head() {
	local url out
	url=$(packaging_url "$1")
	out=$(git ls-remote "$url" HEAD)
	echo "${out%%[[:space:]]*}"
}

# value of a key, empty when file or key missing
meta_get() {
	[[ -f $1 ]] || return 0
	sed -n "s/^$2 = //p" "$1"
}

# content only, renaming a patch doesn't count as a change
patches_sum() {
	local out
	out=$(cat "$1"*.patch | sha256sum)
	echo "${out%% *}"
}

# patches carry PKGBUILD changes only, .SRCINFO is regenerated from it
# run from / since git inside a repo drops paths outside the cwd prefix
# unreadable patches fail too, a guard must not pass on error
validate_patches() {
	local stat
	stat=$(git -C / apply --numstat "$(realpath "$1")"/*.patch) || return 1
	if [[ $stat == *$'\t'.SRCINFO* ]]; then
		echo "$1: patches touch .SRCINFO, keep them to PKGBUILD" >&2
		return 1
	fi
}

# when the patches differ from what the artifacts were built with
has_patches_changed() {
	[[ $(meta_get "$1" patches) != "$2" ]]
}

# bumps on every patch change and never resets, so the suffix only grows
# and a filename is never reused, even across upstream version bumps
next_rev() {
	local rev
	rev=$(meta_get "$1" rev)
	# no record: first build, or existing artifacts being bootstrapped
	[[ -n $rev ]] || { echo 0; return; }
	has_patches_changed "$1" "$2" && rev=$((rev + 1))
	echo "$rev"
}

# hash compare only: commit dates lie (rebase, amend, tz)
has_upstream_moved() {
	local head old
	head=$(remote_head "$1")
	old=$(meta_get "$2" upstream)
	[[ $head != "$old" ]]
}

# upstream commits since our record, what to review against our patches
upstream_log() {
	local old
	old=$(meta_get "$2" upstream)
	[[ -n $old ]] || return 0
	# rewritten history drops our hash from the clone, no range to show
	if ! git -C "$1" cat-file -e "$old^{commit}"; then
		echo "$1: recorded $old gone upstream, force push?" >&2
		return 0
	fi
	git -C "$1" log --oneline "$old..HEAD"
}

# every recorded package file still in dest, -debug may never exist
# no record counts as missing
has_artifacts() {
	local f
	[[ -n $(meta_get "$1" file) ]] || return 1
	while read -r f; do
		[[ -f $2/$f || $f == *-debug-* ]] || return 1
	done < <(meta_get "$1" file)
}

# full rewrite, only after artifacts match this upstream head
# args: clone meta rev patches_sum, then package file paths built
write_meta() {
	local clone=$1 meta=$2 rev=$3 sum=$4 hash date f
	shift 4
	read -r hash date < <(upstream_head "$clone")
	{
		echo "# generated by repack.sh"
		echo "upstream = $hash"
		echo "upstream_date = $date"
		echo "checked = $(now)"
		echo "patches = $sum"
		echo "rev = $rev"
		for f; do
			echo "file = ${f##*/}"
		done
	} > "$meta"
}

# bump check time, keeps the upstream hash artifacts came from
touch_meta() {
	[[ -f $1 ]] || return 1
	sed -i "s/^checked = .*/checked = $(now)/" "$1"
}
